import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";

import { Flex, Layout } from "antd";

import { Header, Content, Footer } from "antd/es/layout/layout";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const headerStyle = {
  textAlign: "center",
  color: "#fff",
  width: "100%",
  height: "auto",
  paddingInline: 10,
  backgroundColor: "#4096ff",
};
export const footerStyle = {
  textAlign: "center",
  color: "#fff",
  backgroundColor: "#4096ff",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="es-MX">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Layout style={{ minHeight: "100vh" }}>
            <Header style={headerStyle}>
              <Navbar />
            </Header>
            <Content>{children}</Content>
            <Footer style={footerStyle}>Footer</Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
