import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";

import { Flex, Layout, Menu, Breadcrumb, theme, Space } from "antd";

import { Header, Content, Footer } from "antd/es/layout/layout";
import Sidebar from "@/components/Sidebar";
import LogoutButton from "@/components/Logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerStyle = {
  padding: 0,
  backgroundColor: "#4096ff",
};
const contentStyle = {
  margin: "0 16px",
  backgroundColor: "#0958d9",
};
const footerStyle = {
  textAlign: "center",
  color: "#fff",
  backgroundColor: "#4096ff",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="es-MX">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Layout
            style={{
              minHeight: "100vh",
            }}
          >
            <Sidebar />
            <Layout>
              <Space
                direction="vertical"
                size="middle"
                style={{
                  display: "flex",
                }}
              >
                <Header
                  style={{
                    display: "flex",
                    padding: 0,
                    paddingRight: 20,
                    justifyContent: "end",
                    backgroundColor: "white",
                  }}
                >
                  <LogoutButton />
                </Header>
                <Content
                  style={{
                    margin: "0 16px",
                    backgroundColor: "white",
                    height: "90vh",
                  }}
                >
                  {children}
                </Content>

                <Footer
                  style={{
                    textAlign: "center",
                  }}
                >
                  Dica ©{new Date().getFullYear()}
                </Footer>
              </Space>
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
